version: '3'
services:
  db:
    build: ./db
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: mysecretpassword
    volumes:
      - pg-volume:/var/lib/postgresql/data
  app:
    build:
      context: .
      dockerfile: Dockerfile
    command: uvicorn server:app --reload --host 0.0.0.0
    volumes:
      - .:/app
    ports:
      - 8000:8000
    depends_on:
      - db
volumes:
  pg-volume: